### ISSUE TITLE
No score on scrapy_rjokes_sample.csv

### ISSUE THREAD

**Issue by dataSci-rigo** [jlee-snn/w210-capstone-humorbot#1]
scrapy_rjokes_sample.csv has no label indicating it's a joke nor does it have a score.

**Comment by jlee-snn** [comment]
Figured out a working solution. 

Check out data set here:
https://github.com/jlee-snn/w210-capstone-humorbot/blob/master/data/dad_jokes_clean_version2.csv

It contains about 1500 clean dad jokes.
